version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "test@123"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  gdp_loader:
    container_name: gdp_loader_container
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_NAME: cloudwalk
      DB_USER: postgres
      DB_HOST: postgres
      DB_PASSWORD: "test@123"
      DB_PORT: 5432
      WORLD_BANK_BASE_URL: https://api.worldbank.org/v2/country/
      INDICATOR: NY.GDP.MKTP.CD
      SELECTED_COUNTRIES: "ARG;BOL;BRA;CHL;COL;ECU;GUY;PRY;PER;SUR;URY;VEN"
      NULL_VALUES: ON
      EXTRACT_GDP_BATCH: 100
      EXTRACT_COUNTRY_BATCH: 50
      BATCHED_INGESTION: "True"
      LOAD_BATCH_SIZE: 25
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres: